### ISSUE TITLE
memory cell issue

### ISSUE THREAD

**Issue by bominn** [KimUyen/ConvLSTM-Pytorch#1]
https://github.com/KimUyen/ConvLSTM-Pytorch/blob/c7b4bd108335a4d6c7d99c00c263346026186b0b/convlstm.py#L114

According to the formula in README, it should be c_next in this line instead of c_cur, right?

**Comment by KimUyen** [comment]
Hi Bominn,
Good observation. Thanks for your feedback.
Yes, it's true that I changed the source different with original paper on this part.
The problem that the convolution layer in my case will change the original image size, so c_next is different shape with c_cur.
Then I used c_cur as peephole input in my implement.
If your c_next keep same size as c_cur. There is no issue to change to c_next in your case.
